/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hianyzasok;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hp
 */
public class HianyzasokGUi extends javax.swing.JFrame {

     private Map<Datum, List<String>> datumok = new TreeMap<>();
     
     DefaultListModel hianyzokModell= new DefaultListModel();
     
     DefaultListModel datumModell= new DefaultListModel();
     
     

     /**
      * Creates new form HianyzasokGUi
      */
     public HianyzasokGUi() {
          initComponents();
          myInit();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane2 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jComboBox1 = new javax.swing.JComboBox<>();
          jComboBox2 = new javax.swing.JComboBox<>();
          jButton2 = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          jList1 = new javax.swing.JList<>();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jPanel2 = new javax.swing.JPanel();
          jTextField1 = new javax.swing.JTextField();
          jTextField2 = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jPanel3 = new javax.swing.JPanel();
          jComboBox3 = new javax.swing.JComboBox<>();
          jScrollPane2 = new javax.swing.JScrollPane();
          jList2 = new javax.swing.JList<>();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("hiányzások feldolgozása");

          jComboBox1.addItemListener(new java.awt.event.ItemListener() {
               public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jComboBox1ItemStateChanged(evt);
               }
          });

          jButton2.setText("Listázz");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
          jScrollPane1.setViewportView(jList1);

          jLabel2.setText("hónap");

          jLabel3.setText("nap");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(70, 70, 70)
                              .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(78, 78, 78)
                              .addComponent(jLabel2)))
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(49, 49, 49)
                              .addComponent(jButton2)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jLabel3))
                    .addContainerGap(26, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jButton2))
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(33, Short.MAX_VALUE))
          );

          jTabbedPane2.addTab("Statisztika", jPanel1);

          jButton1.setText("megszamol");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton1)
                    .addGap(51, 51, 51)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton1)
                         .addComponent(jLabel1))
                    .addContainerGap(198, Short.MAX_VALUE))
          );

          jTabbedPane2.addTab("Tesztelési szakasz", jPanel2);

          jComboBox3.addItemListener(new java.awt.event.ItemListener() {
               public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jComboBox3ItemStateChanged(evt);
               }
          });

          jScrollPane2.setViewportView(jList2);

          jLabel4.setText("Hiányzók listája");

          jLabel5.setText("jLabel5");

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(jPanel3Layout.createSequentialGroup()
                              .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(65, 65, 65)
                              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel3Layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addGap(107, 107, 107)
                              .addComponent(jLabel5)
                              .addGap(53, 53, 53)))
                    .addContainerGap(360, Short.MAX_VALUE))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(57, Short.MAX_VALUE))
          );

          jTabbedPane2.addTab("Hiányzók", jPanel3);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane2)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String szöveg = jTextField1.getText();
          char betu = 'É';
          try {
               betu = jTextField2.getText().charAt(0);
          } catch (Exception e) {

          }
          String ékezetetes = "iéáüűőúóüöÍÉÁŰÚŐÓÜÖ";
          int darab = megszamol(szöveg, betu);
          jLabel1.setText("A " + szöveg + "-ban " + darab + " " + betu + " van.");


     }//GEN-LAST:event_jButton1ActionPerformed

     private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
          jComboBox2.removeAllItems();
          int honap=Integer.parseInt(jComboBox1.getSelectedItem().toString());
         
         TreeSet<Integer> napok= new TreeSet<>();
         
          for (Datum egyDatum : datumok.keySet()) {
               if(egyDatum.getHonap()== honap){
                    napok.add(egyDatum.getNap());
               }
               
          }
          
          for (Integer egyNap : napok) {
               jComboBox2.addItem(String.format("%02d", egyNap));
          }
          
          jComboBox2.setSelectedIndex(0);
     }//GEN-LAST:event_jComboBox1ItemStateChanged

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int honap = Integer.parseInt(jComboBox1.getSelectedItem().toString());
          int nap = Integer.parseInt(jComboBox2.getSelectedItem().toString());
          hianyzokModell.clear();
          Datum keres = new Datum(honap, nap);
          for (String hianyzok : datumok.get(keres)) {
               hianyzokModell.addElement(hianyzok);
          }
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
          String diakNev= jComboBox3.getSelectedItem().toString();
          datumModell.clear();
          jLabel5.setText("Hiányzások: "+diakNev);
          for (Datum datum : datumok.keySet()) {
               for (String elem: datumok.get(datum)) {
                    if(elem.contains(diakNev)){
                         datumModell.addElement(datum.toString()+" "+ elem.substring(elem.length()-7));
                    }
                    
               }
               
          }
     }//GEN-LAST:event_jComboBox3ItemStateChanged

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(HianyzasokGUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(HianyzasokGUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(HianyzasokGUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(HianyzasokGUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new HianyzasokGUi().setVisible(true);
               }
          });
     }

     private void myInit() {
          jList1.setModel(hianyzokModell);
          jList2.setModel(datumModell);
          feltolt("naplo.txt");
          
          TreeSet<Integer> honapok= new TreeSet<>();
          
          for (Datum egyDatum : datumok.keySet()) {  // csak a kulcsokon lehet végig menni
               honapok.add(egyDatum.getHonap());
          }
          
          for (Integer honap : honapok) {
               jComboBox1.addItem(String.format("%02d", honap));
               
          }
          jComboBox1.setSelectedIndex(0);       
  
          comboBoxDiakFeltolt();
          
          

     }

     /**
      * A metódus megszámolja a paraméterként kapott szövegben a paraméterként
      * kapott karaktert. A praméterek értelmezési tartománya
      *
      * @param miben * String típusú változó, ebben számoluk meg a megadott
      * karaktert. Feltesszük, hogy a miben az tuti nem üret
      *
      * @param mit Egy karakter, ezt számoljuk meg.
      *
      * @return a visszaadott egy 0 és a miben változó hossza között lehet [0;
      * miben.length()]
      */
     
     private int megszamol(String miben, char mit) {
          String minta = "[^" + mit + "]";
          return miben.replaceAll(minta, "").length();
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JComboBox<String> jComboBox2;
     private javax.swing.JComboBox<String> jComboBox3;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JList<String> jList1;
     private javax.swing.JList<String> jList2;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTabbedPane jTabbedPane2;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField2;
     // End of variables declaration//GEN-END:variables

     /**
      *
      * @param fileName
      */
     private void feltolt(String fileName) {
          
          //Map<Datum, List<String>>
          
          try {
               RandomAccessFile bemenet = new RandomAccessFile(fileName, "r");
               Datum aktualis= null;
               while(bemenet.getFilePointer()<bemenet.length()){
                    String sor= bemenet.readLine();
                    
                    if(sor.contains("#")){
                         aktualis= new Datum(sor);
                         datumok.put(aktualis, new ArrayList<>());
                    } else{
                      
                       datumok.get(aktualis).add(sor);
                    }
               }
               bemenet.close();
          } catch (IOException e) {
               System.out.println("Hiba: "+ e.getMessage());
          }
          
//          System.out.println(datumok);

     }

     private void comboBoxDiakFeltolt() {
         TreeSet<String> diakok = new TreeSet<>();
         for(Datum kulcs: datumok.keySet()){
              for (String elem : datumok.get(kulcs)) {
                   //Galagonya Alfonz OXXXXXXN
                   diakok.add(elem.substring(0,elem.length()-8));
              }
         }
         
          for (String diak :diakok ) {
               jComboBox3.addItem(diak);
          }
          
          jComboBox3.setSelectedIndex(0);
          
     }

    
}

/*
sourcer structure
# 01 15
Galagonya Alfonz OXXXXXX
# 01 16
Alma Hedvig OOOOOIO
Galagonya Alfonz XXXXXXX
# 01 17
Alma Hedvig OOIOOOO
Galagonya Alfonz XXXXXXX
Maracuja Kolos OOIOOOO

I - izgazolatlan
O - jelen volt
X - igazolt hiányzás
N - nem volt órája
 */
